/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'MyApp.view.MyTabPanelViewModel',
        'Ext.tab.Tab',
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'mytabpanel'
    },
    activeTab: 0,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            border: true,
            title: 'My Tab',
            tabConfig: {
                xtype: 'tab',
                iconAlign: 'top',
                iconCls: 'home_core',
                tooltip: 'Página inicial'
            },
            items: [
                {
                    xtype: 'image',
                    width: '70%',
                    src: 'resources/core-php.svg'
                }
            ]
        },
        {
            xtype: 'panel',
            height: '100%',
            id: 'panelUser',
            itemId: 'panelUser',
            padding: 20,
            title: 'My Tab',
            tabConfig: {
                xtype: 'tab',
                iconAlign: 'top',
                iconCls: 'usuarios_core',
                tooltip: 'Cadastro de permissões'
            },
            items: [
                {
                    xtype: 'form',
                    height: 150,
                    id: 'formUsuario',
                    itemId: 'formUsuario',
                    bodyPadding: 10,
                    url: '../../ext-codeigniter/core.php?action=usuario&metodo=adicionarPermUsuario',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnCadPermUser',
                                    iconCls: 'add1',
                                    text: 'cadastrar',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'reset',
                                    text: 'Limpar',
                                    listeners: {
                                        click: 'onButtonClick1'
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'buscaLogin',
                            itemId: 'buscaLogin',
                            fieldLabel: 'Login da rede:',
                            labelWidth: 115,
                            displayField: 'USUARIO',
                            pageSize: 1,
                            store: 'UserPerfilStore',
                            valueField: 'LOGIN',
                            listeners: {
                                change: 'onComboboxChange',
                                beforerender: 'onBuscaLoginBeforeRender'
                            }
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'buscaUnidades',
                            itemId: 'buscaUnidades',
                            fieldLabel: 'Unidade de atuação:',
                            labelWidth: 115,
                            displayField: 'nomeunidade',
                            pageSize: 1,
                            store: 'Unidades',
                            valueField: 'codunidade',
                            listeners: {
                                beforerender: 'onComboboxBeforeRender',
                                change: 'onComboboxChange1'
                            }
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'buscaSistemas',
                            itemId: 'buscaSistemas',
                            fieldLabel: 'Escolha um sistema:',
                            labelWidth: 115,
                            displayField: 'descricaosistema',
                            pageSize: 1,
                            store: 'Sistemas',
                            valueField: 'codsistema',
                            listeners: {
                                beforerender: 'onComboboxBeforeRender1',
                                select: 'onBuscaSistemasSelect'
                            }
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'buscaPerfis',
                            itemId: 'buscaPerfis',
                            fieldLabel: 'Escolha um perfil:',
                            labelWidth: 115,
                            displayField: 'descricaoperfil',
                            store: 'Perfis',
                            valueField: 'codperfil',
                            listeners: {
                                beforerender: 'onComboboxBeforeRender2',
                                beforequery: 'onBuscaPerfisBeforeQuery',
                                select: 'onBuscaPerfisSelect'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    height: 500,
                    id: 'gridUsuarios',
                    itemId: 'gridUsuarios',
                    title: ' Usuários X Perfis ',
                    store: 'storePermUsuarios',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'login',
                            text: 'Usuario'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'descricao',
                            text: 'Sistema'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'descricaoperfil',
                            text: 'Perfil'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 300,
                            dataIndex: 'nomeunidade',
                            text: 'Unidade'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'statuspermusuario',
                            text: 'Ativo?'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'My Tab',
            tabConfig: {
                xtype: 'tab',
                iconAlign: 'top',
                iconCls: 'sistemas_core',
                tooltip: 'Cadastro de sistemas'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    height: 478,
                    padding: 10,
                    title: 'Sistemas',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'My Tab',
            tabConfig: {
                xtype: 'tab',
                iconAlign: 'top',
                iconCls: 'perfis_core',
                tooltip: 'Cadastro de Perfis'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    height: 478,
                    padding: 10,
                    title: 'Perfis',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'My Tab',
            tabConfig: {
                xtype: 'tab',
                iconAlign: 'top',
                iconCls: 'perfis_core',
                tooltip: 'Cadastro de Perfis'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    padding: 10,
                    title: 'Sistemas',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    padding: 10,
                    title: 'Perfis',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    padding: 10,
                    title: 'Permissoes',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var storePermUsuarios = Ext.getStore('storePermUsuarios');
        var form = Ext.ComponentQuery.query('[itemId=formUsuario]')[0].getForm();
                    	if (form.isValid()) {
                        	//var data = Ext.JSON.encode(form.getValues(false));
        //                     debugger;
                        	var data = form.getValues(false);

                            form.submit({
                            	method: 'POST',
                            	success:function(form, action){
                            		obj = Ext.JSON.decode(action.response.responseText);
                            		if(obj.success === true) {
                            			storePermUsuarios.load();
        		                    	form.reset();
                            		} else {
                            			Ext.Msg.show({
                            			     title:'Mensagem',
                            			     msg: 'Erro ao cadastrar!',
                            			     buttons: Ext.Msg.OK,
                            			     animateTarget: 'btnCadPermUser',
                            			     icon: Ext.window.MessageBox.QUESTION
                            			});
                            		}
                                },
                                failure: function(form, action) {
                                	obj = Ext.JSON.decode(action.response.responseText);
                                	Ext.Msg.show({
                        			     title:'Mensagem',
                        			     msg: obj.msg,
                        			     buttons: Ext.Msg.OK,
                        			     animateTarget: 'btnCadPermUser',
                        			     icon: Ext.window.MessageBox.QUESTION
                        			});
                                }

                            });
                        }
    },

    onButtonClick1: function(button, e, eOpts) {
        // de
        var form = Ext.ComponentQuery.query('[itemId=formUsuario]')[0].getForm();
        var grid =Ext.ComponentQuery.query('[itemId=gridUsuarios]')[0];
        form.reset();
        grid.getStore().removeAll();
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        // debugger;
        var store 	= Ext.getStore('UserPerfilStore');
        var login = Ext.ComponentQuery.query('[itemId=buscaLogin]')[0].getValue();
        var p = store.getProxy();
        p.extraParams = {};
        p.extraParams.login = login;
        store.load();
    },

    onBuscaLoginBeforeRender: function(component, eOpts) {
        component.getStore().load();
    },

    onComboboxBeforeRender: function(component, eOpts) {
        component.getStore().load();
    },

    onComboboxChange1: function(field, newValue, oldValue, eOpts) {
        var store 	= Ext.getStore('Unidades');
        var unidades = Ext.ComponentQuery.query('[itemId=buscaUnidades]')[0].getValue();
        var p = store.getProxy();
        p.extraParams = {};
        p.extraParams.unidades = unidades;
        store.load();
    },

    onComboboxBeforeRender1: function(component, eOpts) {
        component.getStore().load();
    },

    onBuscaSistemasSelect: function(combo, record, eOpts) {
        // debugger;
        // var store = Ext.getStore('storePermUsuarios');
        var codsistema =  Ext.ComponentQuery.query('[itemId=buscaSistemas]')[0].getValue();
        var store = Ext.ComponentQuery.query('[itemId=gridUsuarios]')[0].getStore();
        var p = store.getProxy();
        p.extraParams = {};
        p.extraParams.codsistema = codsistema;
        store.load();
    },

    onComboboxBeforeRender2: function(component, eOpts) {
        component.getStore().load();
    },

    onBuscaPerfisBeforeQuery: function(queryPlan, eOpts) {
        var store = Ext.getStore('Perfis');
        var codsistema =  Ext.ComponentQuery.query('[itemId=buscaSistemas]')[0].getValue();
        store.getProxy().extraParams.codsistema = codsistema;
        store.load();
    },

    onBuscaPerfisSelect: function(combo, record, eOpts) {
        var codsistema =  Ext.ComponentQuery.query('[itemId=buscaSistemas]')[0].getValue();
        var codperfil =  Ext.ComponentQuery.query('[itemId=buscaPerfis]')[0].getValue();
        var store = Ext.ComponentQuery.query('[itemId=gridUsuarios]')[0].getStore();
        var p = store.getProxy();
        p.extraParams = {};
        p.extraParams.codsistema = codsistema;
        p.extraParams.codperfil = codperfil;
        store.load();
    }

});