/*
 * File: app/model/permissoesUsuarios.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.permissoesUsuarios', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'codusuario'
        },
        {
            name: 'login'
        },
        {
            name: 'codsistema'
        },
        {
            name: 'descricao'
        },
        {
            name: 'codperfil'
        },
        {
            name: 'descricaoperfil'
        },
        {
            name: 'codunidade'
        },
        {
            name: 'nomeunidade'
        },
        {
            name: 'statuspermusuario'
        }
    ]
});